name: Tarea diaria programada

on:
  schedule:
    # Se ejecuta todos los días
    - cron: '55 22 * * *'
    
  workflow_dispatch:

jobs:
  tarea-diaria:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
        
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Instalar dependencias
        run: npm ci
        
      - name: Ejecutar tarea programada
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
        run: npm run start
